### PR TITLE
Change build to run on MacOS

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by kaplanlior** [comment]
Hi @gkorland , thanks for this PR. Could you explain the reason for the proposed change?

**Comment by gkorland** [comment]
The current build seems to fail 
On every run: https://github.com/MohGovIL/hamagen-react-native/actions?query=workflow%3ABuild
```
/bin/sh: 1: pod: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kaplanlior** [comment]
Changed at bc2a876d011e9cdb8c0f08ef2ed178241319f688. Will follow up on the tar error the build now has.

**Comment by kaplanlior** [comment]
Changed at bc2a876d011e9cdb8c0f08ef2ed178241319f688. Will follow up on the tar error the build now has.

**Pull request closed without merging**
