### PR TITLE
[FIX] Fix Arabic Copy

### PR DESCRIPTION
**Pull request by Attrash-Islam**
This PR is related to fixing the Arabic copy (There's so many problems in the current copy). I'll be ready if needed to supply the Arabic copy for future changes 🙂

### CODE REVIEW

**Comment by Attrash-Islam** [comment]
@MiriShalev Can we push this forward? if there's something missing in this PR?

**Comment by MiriShalev** [comment]
Hey @Attrash-Islam , thanks for providing a better Arabic translation.

We were already working on a better Arabic version.  (this time with a native-speaker Arabic translator; seems like our first version was horrible).

We expect to ship it with the next version. I'm still keeping your PR open, just in case.

**Comment by Attrash-Islam** [comment]
Yeah.. It's good you're improving the copy! Thanks @MiriShalev

**Comment by ybaruchel** [comment]
Hey @MiriShalev, I am not quite sure about the reason this PR was not merged, the localisation texts provided by @Attrash-Islam seems to be pretty accurate..

**Comment by JonathanLevi** [comment]
That's because they are/were already working on a bettee Arabic version (which may incljde an imorovement for this as well).

@MiriShalev That said, why don't we merge this improvemet so that the next imorovement is going to either have this improvement unchanged, or improved (on top).

As @ybaruchel the busy :-), suggests?

**Comment by hacera-jonathan** [comment]
That's because they are/were already working on a better Arabic version (which may include an improvement for this string translation as well, I presume).

@MiriShalev That said, why don't we merge this improvemet so that the next imorovement is going to either have this improvement unchanged, or improved (on top)..., as @ybaruchel "busy" :-), suggests?

**Comment by Attrash-Islam** [comment]
Screenshot_20200324-232655

I see that the copy was updated in the app, the strange thing is that the master code doesn't match the current app state. How that supposed to be?

**Comment by Attrash-Islam** [comment]
ראיתי שהאפלקציה קיבלה עדכון בשפה הערבית שלא תואם לזה שיש בקוד הנוכחי במאסטר. עבר יומיים מאז העדכון האחרון של האפלקציה.

נראה לי שמפתחי האפלקציה צריכים לדאוג יותר לעניין השקיפות ודווקא אחרי הצהרות השב"כ והמעקב הדיגטאלי.

אני מקווה שאני טועה כי התקנתי ומחקתי ואז התקנתי רק בגלל שזה אופן סורס ומשדר בטחון שמה שרואים במאסטר זה מה שרץ באפלקציה.

**Comment by Attrash-Islam** [comment]
I got the updated copy through CDN and it looks good. Closing the PR for now 🙂

**Comment by GelosSnake** [comment]
Hi,

Due to translation problems and the impact on the large multi-language audience a workaround was implemented to update the translation from the CDN.
https://github.com/MohGovIL/hamagen-react-native/blob/584918cffc61836d6543bba85083f2eac6e41e15/src/config/config.ts
https://gisweb.azureedge.net/config.json

So this is why you see a difference, no hidden source or similar.

**Comment by Attrash-Islam** [comment]
Yeah, Tomer Zait explained it to me. Thanks for the clarification 👍🏻

**Pull request closed without merging**
