### PR TITLE
Added Tigrinya (ትግርኛ) language translation:

### PR DESCRIPTION
**Pull request by oyd11**
More on Issue #142 , hopefully closing it, and production ready.

 * locale '`ti`' (`iso 639-1` and `locale` code)
 * Using the English prompts as the source for translation
 * Translation contributed by Araya Kassa. I have basic knowledge of Tigrinya, enough to verify most of this, it seems like a good translation in context, the translator has background in the healthcare system, and is a native speaker of Tigrinya.
 * `npm test` passed successfully.
 * `npm start` runs successfully, but I did not test this yet.

### CODE REVIEW

**Comment by oyd11** [comment]
I've closed PR #156 by mistake (after some rebase error I had, wanted to keep this up-to-date with `master`).

**Comment by oyd11** [comment]
Translation was reviewed by native speaker volunteer from the "Eritrean Women's Community Center in Israel" [ https://www.eritreanwomenscenter.org ].
I suggest this is iterated into the next release, along with some explanation, it was just reported that two foreign-nationals in Southern-Tel-Aviv, were diagnosed with COVID-19, which is one of the denser Tigrinya-speaking population in Israel right now. Thank you.

**Comment by oyd11** [comment]
Can anyone merge this translation? It's verified since 5th-April-2020 (a little over a month),
and there's still a highly dense urban population which speaks this language predominantly, a lot of them working in the service industry now. Please merge.

Note that the Minister - does release Videos in Tigrinya : (Tigrinya subtitles in this case) :
מיגון פנים - טיגרית
https://www.youtube.com/watch?v=dEYbG5nrXZw

**Comment by kaplanlior** [comment]
Hi @oyd11 , thanks for this PR and your effort. At the moment we don't accept any new translations. I'm adding a translations tag to this PR, so it could be used easily when translations would be accepted again.

**Comment by sltanhs** [comment]
حسبي الله ونعم الوكيل منك يا ابو بشار المنحرف الغدار الخاين المخادع الكذاب ليش عادك تحلف من كذب وهذا ماهو زنوه

**Comment by sltanhs** [comment]
حسبي الله   ##ونعم الوكيل منك يا ابو بشار المنحرف الغدار الخاين المخادع الكذاب ليش عادك تحلف من كذب وهذا ماهو

**Pull request closed without merging**
